### ISSUE TITLE
建议出一个置顶

### ISSUE THREAD

**Issue by Willoneday** [jxlpzqc/TMSpeech#12]
视频打开全屏后就看不了了

**Comment by am009** [comment]
其实现在窗口已经置顶了。视频打开全屏看不了这个问题得再详细看看怎么回事

**Comment by ZiLoong-L** [comment]
> 其实现在窗口已经置顶了。视频打开全屏看不了这个问题得再详细看看怎么回事

好像现在失效了？实测在聚焦于Edge浏览器时，字幕窗口会被挡在下面

**Comment by ZiLoong-L** [comment]
> > 其实现在窗口已经置顶了。视频打开全屏看不了这个问题得再详细看看怎么回事
> 
> 好像现在失效了？实测在聚焦于Edge浏览器时，字幕窗口会被挡在下面

测试了一下，应该是Edge浏览器的问题哈哈哈哈，也有其他水友遇到过Edge浏览器强制置顶的问题。

**Comment by ZiLoong-L** [comment]
> > 其实现在窗口已经置顶了。视频打开全屏看不了这个问题得再详细看看怎么回事
> 
> 好像现在失效了？实测在聚焦于Edge浏览器时，字幕窗口会被挡在下面

测试了一下，应该是Edge浏览器的问题哈哈哈哈，也有其他水友遇到过Edge浏览器强制置顶的问题。
