### ISSUE TITLE
后台运行闪退

### ISSUE THREAD

**Issue by sino1641** [jxlpzqc/TMSpeech#17]
最新版本稳定复现，使用TMSpeech识别时点击任务栏切换其他程序就会闪退。
不切窗口就可以一直正常识别。
附dmp：
[TMSpeech.GUI.exe.31204.dmp](https://github.com/jxlpzqc/TMSpeech/files/13556915/TMSpeech.GUI.exe.31204.dmp)

**Comment by am009** [comment]
尝试修复，应该是修复了吧，但是我本地复现不了😂。有时间的话可以试试新的版本，看看还有没有这个问题。如果其他人也有相同问题可以在这里回复

似乎是因为[WPF 4.5](https://stackoverflow.com/questions/14336750/upgrading-to-net-4-5-an-itemscontrol-is-inconsistent-with-its-items-source)的问题。

**Comment by sino1641** [comment]
新版本稳定输出，不再闪退~
谢谢！
