### ISSUE TITLE
无法成功下载，失败提示需要授权

### ISSUE THREAD

**Issue by moriaty2013** [jxlpzqc/TMSpeech#20]
如题所示情况，无法成功下载
![下载需要授权](https://github.com/jxlpzqc/TMSpeech/assets/5159076/ad20960c-b29d-413e-8ec6-c3e304d29784)

**Comment by am009** [comment]
奇怪，没见过啊

**Comment by moriaty2013** [comment]
我使用Chrome和edge浏览器下载都是同样的情况。edge还生成了一个下载失败的txt文件，不过同样打不开..
![无法下载-edge](https://github.com/jxlpzqc/TMSpeech/assets/5159076/7beb8016-3591-45ff-801f-70844f47080f)

**Comment by moriaty2013** [comment]
可以给一个其他的下载方式吗？

**Comment by am009** [comment]
我试试传到Gitee： https://gitee.com/am009/TMSpeech/releases/v0.0.1-rc3

**Comment by am009** [comment]
Gitee居然限制release大小不能超过100M，我只好压缩包分四个卷

**Comment by csukuangfj** [comment]
> 我试试传到Gitee： https://gitee.com/am009/TMSpeech/releases/v0.0.1-rc3

github 上 release 一个版本时，可以传不受限制个数的文件。单个文件不超过 2GB. 建议把文件放 github release 。
