### ISSUE TITLE
希望加入字幕锁定功能

### ISSUE THREAD

**Issue by 2017dyu** [jxlpzqc/TMSpeech#24]
字幕锁定后无法拖动和调整大小，无法调整设置和查看历史记录，就像音乐软件的歌词锁定那种

**Comment by ZiLoong-L** [comment]
支持！不过可惜好像已经很久没有更新啦哈哈哈

**Comment by jxlpzqc** [comment]
@2017dyu  @ZiLoong-L  最新版本已经支持字幕锁定。

**Comment by ZiLoong-L** [comment]
> @2017dyu @ZiLoong-L 最新版本已经支持字幕锁定。

哇感谢大佬！！
