### ISSUE TITLE
请问，字幕前面的时间线怎么取消

### ISSUE THREAD

**Issue by Ventrilo404** [jxlpzqc/TMSpeech#32]
例如：16:15:05: 现在时刻下午四点十五分
我想要只保留纯文本：现在时刻下午四点整十五分
不要前面的16:15:05

纯小白，不会代码，选项里没找到
文件夹里能点开的都点了，看不懂……
望解答

**Comment by am009** [comment]
可以先安装VSCode，然后使用VSCode的正则替换功能，把时间戳替换为空。  `[0-9][0-9]:[0-9][0-9]:[0-9][0-9]: `
![image](https://github.com/jxlpzqc/TMSpeech/assets/23314210/4e3a197a-9811-4895-94f0-f5ecacb345d0)

**Comment by Ventrilo404** [comment]
成功了，谢谢
