### ISSUE TITLE
麦克风输入无法识别

### ISSUE THREAD

**Issue by 1547481339** [jxlpzqc/TMSpeech#4]
我的笔记本电脑，使用耳机或者笔记本麦克风均无法识别，播放音频文件可以识别，请问是哪里设置的问题吗

**Comment by am009** [comment]
麦克风无法识别是正常的，我们用的那个API仅抓取了电脑播放的声音

**Comment by 1547481339** [comment]
哦，了解，我试了一下腾讯会议，开了录制也不能识别，录制的音频文件播放可以识别
另外，我测试的双轨录音也是只能识别左声道的音频，右声道识别不了

**Comment by csukuangfj** [comment]
sherpa-onnx 只能识别一个通道。 如果你有多个通道的话，需要调用者决定去识别哪个通道.

**Comment by jxlpzqc** [comment]
如果要多个通道，可能需要在把数据喂给sherpa-onnx之前做一个混音操作。

**Comment by a630050** [comment]
請問可以增加API改掉用麥克風輸入的聲音嗎?

**Comment by jxlpzqc** [comment]
@a630050  @1547481339 目前最新版本已经支持麦克风输入，请前往 Releases 下载最新版本试用
