### ISSUE TITLE
新版無法work

### ISSUE THREAD

**Issue by a630050** [jxlpzqc/TMSpeech#40]
play按鈕(是錄音還是啟動? 按了啟動後無法停止 暫停鈕跟停止鈕都無法work
另外字幕也沒有轉錄出來
我是win11 有開啟混音 但音源怎麼選看起來都沒有反應

**Comment by ZiLoong-L** [comment]
新版本的这个是不自带models的，我是从旧版本中拷贝过来才能用，不知道你是不是因为这个原因？

**Comment by a630050** [comment]
重啟之後 Play鈕可以正常啟閉了 ，如上面朋友所述確實是沒有模型的問題，以為sherpa-Onnx是自帶的@@ 感謝

**Comment by ZiLoong-L** [comment]
> 重啟之後 Play鈕可以正常啟閉了 ，如上面朋友所述確實是沒有模型的問題，以為sherpa-Onnx是自帶的@@ 感謝

不客气~想问下您有尝试过在“资源”那里下载其他模型嘛？我想在Github上下载后手动安装模型，但是不知道这里附加的额外模型应当放到哪个文件夹里？
