### ISSUE TITLE
鎖定後，無按鍵可無法取消鎖定?

### ISSUE THREAD

**Issue by a630050** [jxlpzqc/TMSpeech#41]
鎖定後，滑鼠可穿透，但無按鍵可無法取消鎖定?
程式列或系統列也沒有icon可以關閉或修改設定
可以加上嗎 謝謝大佬!

**Comment by ZiLoong-L** [comment]
右下角任务栏小图标那里，右键应用图标就能看到“解锁字幕”的地方
