### ISSUE TITLE
启动失败！

### ISSUE THREAD

**Issue by yinhong-zhou** [jxlpzqc/TMSpeech#42]
启动失败！Value cannot be null（parameter 'key'）
下载最新版启动报错

**Comment by yinhong-zhou** [comment]
下载最新版启动报错

**Comment by jxlpzqc** [comment]
请确认一下配置页面中是否配置好了音频源和识别器

**Comment by yinhong-zhou** [comment]
已解决 感谢！

**Comment by bjmyxd** [comment]
启动失败！
麻烦大神看一下，谢谢！
![1](https://github.com/user-attachments/assets/454941e4-7bcf-446e-809c-ef7a4efcbaee)
![2](https://github.com/user-attachments/assets/448be342-914e-4360-b0f3-659ec1bdfb77)
![3](https://github.com/user-attachments/assets/3b3fc936-5f35-439b-b9bc-d980d0fa5939)

**Comment by am009** [comment]
可以尝试一下带模型的最新版，优化了第一次使用的体验，应该是开箱即用的。有什么问题欢迎再反馈！
国内下载：https://gitee.com/am009/TMSpeech/releases/tag/v0.4.2
Github：https://github.com/jxlpzqc/TMSpeech/releases/tag/v0.4.2
