### ISSUE TITLE
启动失败！麻烦大神看一下

### ISSUE THREAD

**Issue by bjmyxd** [jxlpzqc/TMSpeech#48]
启动失败！
![1](https://github.com/user-attachments/assets/2095c991-34f2-45d7-bf3c-a46ea72b9870)
![2](https://github.com/user-attachments/assets/0f1f487b-c6a5-4166-a541-e11dd1c55cf1)
![3](https://github.com/user-attachments/assets/3be569a4-556d-46da-a01c-769cf83f5ef6)

**Comment by jxlpzqc** [comment]
@bjmyxd  请在资源中下载模型并在识别器中选择模型

如果想使用自定义模型，请使用“浏览”选择您的自定义模型
