### ISSUE TITLE
如何更换语音模型呢

### ISSUE THREAD

**Issue by SarahSmitho** [jxlpzqc/TMSpeech#5]
如题

**Comment by am009** [comment]
是pytorch的其他模型，还是sherpa-onnx框架的模型？后者可以在设置里修改路径。现在的release带的是sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20 

https://k2-fsa.github.io/sherpa/onnx/pretrained_models/online-transducer/zipformer-transducer-models.html

**Comment by SarahSmitho** [comment]
![1688110230044](https://github.com/jxlpzqc/TMSpeech/assets/56591685/f294b086-b52f-4fe3-9d91-f80d8e7ffdef)
我是按照这个教程得到的这个模型

**Comment by SarahSmitho** [comment]
![image](https://github.com/jxlpzqc/TMSpeech/assets/56591685/167e2d7f-9736-49be-be37-c8faf9b8afb1)
和工程里的不一样，我是做安卓的，不太了解C#的架构

**Comment by am009** [comment]
那直接在设置这里修改路径试试。正好对应四个文件
![image](https://github.com/jxlpzqc/TMSpeech/assets/23314210/d7ceaf05-fc03-4948-809e-d27f47d15aa5)

**Comment by csukuangfj** [comment]
> ![1688110230044](https://user-images.githubusercontent.com/56591685/250024794-f294b086-b52f-4fe3-9d91-f80d8e7ffdef.jpg) 我是按照这个教程得到的这个模型

你用的是非流式 (即 offline)。这个项目需要流式（即 online)

https://github.com/jxlpzqc/TMSpeech/blob/24e1e36c1c29fe4cbdd519fe0b5b0a8d569bed88/TMSpeech.GUI/SpeechCore.cs#L46


如果你给一个 非流式的模型，会报错的.

**Comment by SarahSmitho** [comment]
可以换成非流式吗

**Comment by SarahSmitho** [comment]
![image](https://github.com/jxlpzqc/TMSpeech/assets/56591685/6c97d6c1-afd1-4dd3-9725-4cec774452ac)
把我们的示例代码引过来，然后我需要GUI界面

**Comment by am009** [comment]
是什么需求啊，非流式模型一般用来解码文件，不太需要这样实时展示吧。

**Comment by SarahSmitho** [comment]
需求是离线实时维汉翻译，因为作者没有给维吾尔语的模型，我自己训练了一个，因为那个教程只有非流式的脚本，我自己改的脚本训练出来的效果很差，所以只能用非流式的模型

**Comment by am009** [comment]
非流式的模型不太好做实时吧，如果一边录音，一边切割出小块喂给模型的话，如果切割到了一个字的中间会出问题？这一块我也不太懂。如果要直接识别文件的话，可以直接用命令行，不一定非要图形界面。
