### ISSUE TITLE
V0.4.1版本语音记录文件不出现

### ISSUE THREAD

**Issue by Sheart-out** [jxlpzqc/TMSpeech#50]
语音识别结果未能成功输出至 我的文档/TMSpeechLogs 目录。 
火绒剑未能检测到TMSpeech.exe写入文件操作
TMSpeech软件History中有记录识别到的文本，但没有将文本输出至文件

系统：Win11
模型：中英双语

**Comment by 666nbplus** [comment]
你在说什么 


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年11月20日 19:57 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [jxlpzqc/TMSpeech] V0.4.1版本语音记录文件不出现 (Issue #50) |

语音识别结果未能成功输出至TMSpeechLogs目录。
火绒剑未能检测到TMSpeech.exe写入文件操作
History中可见识别记录

系统：Win11
模型：中英双语

**Comment by am009** [comment]
感谢反馈，更新到新版的时候这个功能忘做了，已经在最新版0.4.2重新实现了这个功能。
