### ISSUE TITLE
win10 打开程序后没反应，看不到任何界面

### ISSUE THREAD

**Issue by zmajiabilly** [jxlpzqc/TMSpeech#7]
win10 打开程序后没反应，看不到任何界面。  用管理员运行也还是不行。

**Comment by am009** [comment]
运行的是TMSpeech.GUI.exe吧？没有任何报错框吗？

（还有其他人有遇到这个问题吗？也评论一下吧

**Comment by zmajiabilly** [comment]
找到了，打开后默认在电脑左上角，一行红字，不容易发现。 抱歉了哈。
